### ISSUE TITLE
Some navigation items don't work under certain conditions

### ISSUE THREAD

**Issue by donjo** [cloudflare/workers.cloudflare.com#104]
If you load workers.cloudflare.com and click "Sites" or "Built With" in the navigation, the URL will change in your browser but nothing will load until you manually refresh the page. Using the browser's native back button to go back to the workers.cloudflare.com will result in the same thing happening there.  

However, it seems like you can go from "Sites" to "Built With" and it works fine. Maybe just a problem in going between `/` and `/*`?

**Comment by signalnerve** [comment]
fixed with #105, thanks!
