### ISSUE TITLE
docs: incorrect command for bulk delete

### ISSUE THREAD

**Issue by calendee** [cloudflare/workers.cloudflare.com#140]
The i[nstructions for bulk deleting with Wrangler](https://developers.cloudflare.com/workers/cli-wrangler/commands#delete-3) show the incorrect command.

```
wrangler kv:key delete --binding= [--env=] [--preview] [--namespace-id=] $FILENAME
```

This should actually be:

```
wrangler kv:bulk delete --binding= [--env=] [--preview] [--namespace-id=] $FILENAME
```

In fact, the provided Usage sample shows the correct command.

```
wrangler kv:bulk delete --binding=MY_KV allthethingsdelete.json
```

**Comment by koeninger** [comment]
https://github.com/cloudflare/cloudflare-docs/pull/444
