### ISSUE TITLE
Google bots unable to crawl

### ISSUE THREAD

**Issue by pjatx** [cloudflare/workers.cloudflare.com#141]
Currently, Google Crawlers are unable to crawl https://workers.cloudflare.com. Because of this, we're not able to run any ads or start ranking for any content on the site. 

I think this may be because we don't have a valid robots.txt file or sitemap for it to read. You can check the URL with this Google tool to see what I mean: https://search.google.com/test/mobile-friendly.

Think it should be relatively easy to get a sitemap and robots.txt up with Gatsby plugins.

**Comment by signalnerve** [comment]
closed by 35639b1d4229f16cdc30e218b11dec7bfcb9ef58
