### ISSUE TITLE
Snippet in hero (on landing page) out of date

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/workers.cloudflare.com#189]
Current snippet content:
```bash
npm install -g @cloudflare/wrangler
wrangler login
wrangler generate hello
cd hello
wrangler subdomain world
wrangler publish
```

for wrangler v2 it should probably be:
```bash
npm install -g wrangler
wrangler login
wrangler init hello -y 
cd hello
wrangler publish
```

**Comment by threepointone** [comment]
correct! If the user doesn't have a subdomain then we point them to the dashboard to make one. We have an open task for doing that automatically from wrangler which we should def do for 2.1
