### ISSUE TITLE
Horizontal scroll persistence

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare/workers.cloudflare.com#20]
When you hit back from an individual project page, you lose your horizontal scroll position for the collections on the index page.

**Comment by signalnerve** [comment]
bumping this as i review our post-launch milestone: i still don't think this is huge priority, but more importantly i think it will be a huge time sink (and we have two weeks). @adamschwartz i'd like to remove this from the milestone, let me know if you feel differently!

**Comment by adamschwartz** [comment]
FBM for now
