### ISSUE TITLE
Create content contribution guidelines

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare/workers.cloudflare.com#22]
![image](https://user-images.githubusercontent.com/154613/69391472-eb49bb80-0ca0-11ea-8bc6-3ef68c942014.png)

**Comment by signalnerve** [comment]
i'm ok to punt on this one for our next milestone, though i've been doing less data input recently so i'm not sure how relevant it is. if we feel like it's important and @adamschwartz has bandwidth, happy to keep it in. lmk

**Comment by adamschwartz** [comment]
FBM for now
