### ISSUE TITLE
Mention content licensing on the site somewhere

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare/workers.cloudflare.com#47]
We already plan to mention licensing in this repo and on the content submission form. But we’re considering mentioning something to the effect of "All project content licensed under [CC By-SA](https://creativecommons.org/licenses/by-sa/4.0/)" on the site somewhere.

cc @signalnerve

**Comment by signalnerve** [comment]
cc @ashleygwilliams

**Comment by adamschwartz** [comment]
Closed by https://github.com/cloudflare/workers.cloudflare.com/commit/3e2da81915aa53799471e55f9ec8104b193510c2
