### ISSUE TITLE
List collection membership on individual project page

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare/workers.cloudflare.com#59]
Suggestion from @ashleygwilliams 

Possible location for display:

![image](https://user-images.githubusercontent.com/154613/72649242-1ff98c80-394b-11ea-94a0-5957a0097aad.png)

**Comment by signalnerve** [comment]
@adamschwartz, do you want to fill out this issue w/ our discussion from earlier today?

**Comment by adamschwartz** [comment]
I think we decided first step was for me to make a design mock with overall set of changes we think we’ll want related to this change.

So minimally:

- Project page sidebar design for list collection membership(s)
- Project page sidebar design for list of project features
- Project page recommended projects improvements

And possibly:

- Individual collection pages
- Feature pages (e.g. `/built-with/workers-kv/`)
- Home & project page links to these

Once we have that we can decide how to prioritize the work from there.
