### ISSUE TITLE
Horizontal Scrolling and Getting Stuck

### ISSUE THREAD

**Issue by mattlockyer** [cloudflare/workers.cloudflare.com#84]
I can't click and drag and I don't have a horiz scrolling mousewheel right now (travelling) so I got stuck trying to move the carousel to the right.

Trackpad works fine, but without a scrollbar or some arrow on the sides, this feels like a bad pattern.

I would add subtle arrows on the sides for desktop with a hover that makes them bolder so they don't get in the way too much. User clicks and it should slide the carousel over about 80% of screen.

**Comment by dmitryyankowski** [comment]
Bump! I can't horizontally scroll either :) Like @mattlockyer said.. arrows would be awesome at the ends!
