### ISSUE TITLE
Last project in each collection rendered inside a collection spacer

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare/workers.cloudflare.com#89]
![image](https://user-images.githubusercontent.com/154613/73407443-1d8e1f80-42c7-11ea-9fd4-c41b64dc16e4.png)

![image](https://user-images.githubusercontent.com/154613/73407470-37c7fd80-42c7-11ea-9bba-aa549a64cf6f.png)

**Comment by signalnerve** [comment]
per @adamschwartz and i chatting, this is probably an SSR bug, specifically around the bookmark component rendering. will prioritize this over the next couple days

**Comment by adamschwartz** [comment]
@signalnerve Closing this as I believe it’s been resolved for a while now (ever since the ESR-related refactor).
