### ISSUE TITLE
Submitting 3rd party sites

### ISSUE THREAD

**Issue by tomByrer** [cloudflare/workers.cloudflare.com#91]
Hi, I'm updating my [awesome-cloudflare-workers](https://github.com/tomByrer/awesome-cloudflare-workers).  I have links that might work better here at built-with-workers, then I can focus more on tooling & non-site examples.

Seems your form expects the site owner to enter the suggestion, vs a visitor suggesting someones' site.  
Could a 3rd party suggest others' sites?  I don't want my email address attached as a 'site owner' of a site I don't own ;).

**Comment by signalnerve** [comment]
that's awesome, thanks @tomByrer! that's a great question that we haven't considered - cc @adamschwartz and @ashleygwilliams on how we can best handle that. we can def update/change the form but we need to plan a bit around how we handle submissions from people that aren't the owner of a project. we'll make sure to chat about this soon!

**Comment by adamschwartz** [comment]
I see no problem with folks submitting others’ sites. However, after someone submits, we may want to _then_ contact the owner/creator before displaying the project on Built with Workers.

**Comment by tomByrer** [comment]
That's a good point @adamschwartz; the ones I'm intending to submit are most likely found on Github with their source, or via a blog post where they openly talk about their infrastructure.

There is 1 major corp that said in a DevOps that they were going to use workers, so due to your concern I would directly ask if they want to be listed.

**Comment by tomByrer** [comment]
Perfect example:

https://www.axios.com/new-axios-website-google-amp-563e62ba-8708-4965-8f5e-3216bd268383.html

> Cloudflare Edge Workers: We’re leveraging Edge Worker technology to manage the gradual rollout, perform A/B testing, and perform ESI-style page-stitching so that you can have the fastest possible site, served directly from the cache closest to you.

**Comment by tomByrer** [comment]
Also, not sure how to add an API, since there is no 'website'.
@signalnerve what do you think about this?
https://github.com/amodm/api-covid19-in#api-covid-19-india

(The [boss](https://twitter.com/eastdakota/status/1239427518437838848) might like you to add it ;) )
